export const COLUMN_NAMES = {
  NAME: "Name",
  STATUS: "Status",
  TICKET: "Ticket",
  MR: "MR",
  ASSIGNEE: "Assignee",
  REVIEWERS: "Reviewers",
  APPROVALS: "Approvals",
} as const;

export const STATUS_VALUES = {
  IN_DEV: "IN DEV",
  READY_FOR_REVIEW: "READY FOR REVIEW",
  CONFLICTS_ISSUES: "CONFLICTS/ISSUES",
  READY_TO_MERGE: "READY TO MERGE",
  TESTING: "TESTING",
  RESOLVED: "RESOLVED/READY FOR PROD",
  DONE: "DONE",
  PENDING_COMMENTS: "PENDING COMMENTS",
  CLOSED: "CLOSED",
} as const;

